### ISSUE TITLE
It rendered a video but gave this error:

### ISSUE THREAD

**Issue by james-beans** [rizekTheGuy/JschlattReactionsMaker#1]
# So, I made it render a 12 min and 5 second video and after it rendering properly it gave this error but still outputed the render?
![Screenshot 2024-07-27 222339](https://github.com/user-attachments/assets/9c3fa535-e48d-4bca-bfb5-c4518ecfd26f)
![Screenshot 2024-07-27 222400](https://github.com/user-attachments/assets/08eefeee-7be3-45b4-a5e0-01097598c267)
![Screenshot 2024-07-27 222435](https://github.com/user-attachments/assets/dec560b8-864a-4251-9bfd-11dd85cb6c04)

pls fix and don't abandon this project.

**Comment by PYL29** [comment]
Probably .mov is not supported. Convert it to mp4.

**Comment by rizekTheGuy** [comment]
your video is 12 min long and music.mov is 8 so its telling you that music.mov is shorter so it cant cut it to fit the video, all you have to do is make music.mov longer than the video you put :D

**Comment by james-beans** [comment]
> your video is 12 min long and music.mov is 8 so its telling you that music.mov is shorter so it cant cut it to fit the video, all you have to do is make music.mov longer than the video you put :D

Thanks. I didn't notice that.
